config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'root#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :words, only: [:index, :new, :create]
  resources :choices, only: [:index, :create]
  resources :votes, only: [:index, :create]
  resources :profile, only: [:index]

  get 'i/:slug', to: 'words#show', as: 'word'

  resources :sessions, only: [:create, :destroy]
end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  skip_before_action :check_logged_in, only: :index

  def index
  end
end

app/views/root/index.html.slim
.main_container
  - content_for :stylesheets do
    = stylesheet_link_tag 'root'

  h1.root_logo
    = image_tag 'logo.png', class: 'root_logo_img', alt: 'みんヨミ！ ～みんなの読み方教えてよ！～'

  | なかなか読み方が定まらないことの多いIT用語、そんなIT用語を中心に、いろいろな英単語の読み方に投票していきませんか？
  hr

  = link_to words_path do
    | 単語一覧
  br
  = " 現在 #{Word.count} 項目！"
  br
  br
  - if current_user
    = link_to new_word_path, class: 'new_word_link' do
      button.button_common type="submit"
        | 単語を追加する
  - else
    = link_to '#', onClick: "void(document.querySelector('#sign_in_with_google').click())"
      | ログイン
    | して単語を追加！
  hr

  h2 最近追加された単語
  - Word.order(created_at: :DESC).limit(10).each do |word|
    = link_to word.name, word_path(word.slug)
    br
  hr

  h2 最近投票された単語
  - Word.order(last_voted_at: :DESC).limit(10).each do |word|
    = link_to word.name, word_path(word.slug)
    br

- if current_user&.admin?
  hr

  | ver1.0リリースまでにやりたいもの
  ul
    li ログを残す（荒らし対策）
    li 不要ファイル整理

  | ver1.0リリースのタイミングでやること
  ul
    li MITライセンスにする

  | 要検討
  ul
    li タグ編集機能
    li 単語や選択肢を追加する際の確認画面に戻るボタンがほしい
    li タグというのが何なのか分かりづらい？
    li ログイン済みユーザーの投票数も表示できるようにする
    li Twitter Card の画像を動的に生成する
    li votes のパーティション化
    li Sign in with Google ボタンの見た目をどうにかする
    li admin専用に単語削除機能、選択肢削除機能を追加
    li 広告表示
    li 個人設定で広告を非表示にできるようにする
    li ログイン後に直前のページに戻る
    li 読み方表示を平仮名とカタカナで切り替えられるようにしたい（しないかも）
    li .jsの有無で「もしかして？」表示
    li Sler -> もしかして SIer?
    li メンテナンスモード実装（読み取りのみ可）
  hr

  = link_to "/words", words_path
  = " 現在 #{Word.count} 項目！"
  br
  = link_to "/choices", choices_path
  = " 現在 #{Choice.count} 項目！"
  br
  = link_to "/votes", votes_path
  = " 現在 #{Vote.count} 項目！"
  = " ユーザーの投票 #{Vote.where(user: current_user).count} 項目！"